# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: myuanz/rsync-deploy@master
        env:
          DEPLOY_KEY: ${{ secrets.PRIVATE_KEY }}   # 引用配置，SSH私钥
          ARGS: "-avz -e -c -r"
          SERVER_PORT: 22
          FOLDER: ./  # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: '111.231.79.44'
          USERNAME: 'root'
          SERVER_DESTINATION: /home/www/cn_maixpy    # 部署到目标文件夹
